language: java
jdk: oraclejdk8
# https://docs.travis-ci.com/user/multi-os/
os:
  - linux
#  - osx

#https://docs.travis-ci.com/user/hosts
addons:
  hosts:
    - travis
  
#https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
# quite not to consumes more than the 4MB of authorized logs
# https://github.com/travis-ci/travis-ci/issues/1382
install: "mvn clean install -DskipTests"
#script: "mvn deploy -DskipTests --settings travis-maven-settings.xml"
script: "mvn install"
#deploy: "mvn deploy --settings travis-maven-settings.xml"
